# Generated by Django 5.1.6 on 2025-06-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='youtube_video_id',
        ),
    ]
