# Generated by Django 5.1.6 on 2025-04-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
