# Generated by Django 5.1.6 on 2025-05-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='revote_count',
            field=models.IntegerField(default=0),
        ),
    ]
