# Generated by Django 5.1.6 on 2025-05-12 16:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_vote_revote_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'poll')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='revote_count',
        ),
    ]
