# Generated by Django 5.1.6 on 2025-06-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_vote_unique_together_remove_vote_revote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='revoted',
            field=models.BooleanField(default=False),
        ),
    ]
