# Generated by Django 5.1.4 on 2025-04-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
