# Generated by Django 5.1.6 on 2025-05-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_question_order_alter_question_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='page',
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='SurveyPage',
        ),
    ]
