# Generated by Django 5.1.6 on 2025-05-05 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_remove_question_page_alter_question_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='attempt',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='surveyresult',
            unique_together={('user', 'survey', 'attempt')},
        ),
    ]
